import React, { Fragment } from 'react'
import Counter from '../components/counter/Counter'

const Home: React.FC = () => {
  return (
    <Fragment>
      <h1>Welcome my portfolio</h1>
      <p>
        Hello and welcome!This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around
      </p>
      <Counter />
    </Fragment>
  )
}
export default Home
